name: todolist
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  provider: ^6.0.2
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.3

  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: ShadowsIntroLight
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf